#!/bin/bash

if test ! -d $HOME/.nvm
then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  source .nvm/nvm.sh
fi

if test ! $(which node)
then
  nvm install node
fi

if test ! $(which eslint)
then
  npm install -g eslint
fi

if test ! $(which netlify)
then
  npm install -g netlify-cli
fi

if test ! $(which prettier)
then
  npm install -g prettier
fi

if test ! $(which tsc)
then
  npm install -g typescript
fi