#!/bin/bash

case $(uname -s) in 
  "Darwin")
    set is_darwin = 1
    echo "Executing `dirname $0`/bootstrap-darwin"
    `dirname $0`/bootstrap-darwin
    ;;
  "Linux")
    set is_linux = 1
    if test -f /usr/bin/lsb_release
    then
      echo "Executing `dirname $0`/bootstrap-ubuntu"
      `dirname $0`/bootstrap-ubuntu
    fi
    if test -f /mnt/c/Windows/System32/wslconfig.exe
    then
      set is_wsl = 1
      echo "Executing `dirname $0`/bootstrap-wsl"
      `dirname $0`/bootstrap-wsl
    fi
    ;;
  *)
    ;;
esac;

# Node

`dirname $0`/bootstrap-node

# Rust

if [ ! -f ~/.cargo/bin/rustup ]
then
  curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path
fi


