#!/bin/bash

if test ! $(which node)
then
  echo "Node must be installed!"
  exit
fi

if test ! $(which eslint)
then
  npm install -g eslint
fi

if test ! $(which netlify)
then
  npm install -g netlify-cli
fi

if test ! $(which prettier)
then
  npm install -g prettier
fi

if test ! $(which tsc)
then
  npm install -g typescript
fi