#!/bin/bash

case $(uname -s) in 
  "Darwin")
    set is_darwin = 1
    echo "Executing `dirname $0`/bootstrap-darwin"
    `dirname $0`/bootstrap-darwin
    ;;
  "Linux")
    set is_linux = 1
    if test -f /usr/bin/lsb_release
    then
      echo "Executing `dirname $0`/bootstrap-ubuntu"
      `dirname $0`/bootstrap-ubuntu
    fi
    if test -f /mnt/c/Windows/System32/wslconfig.exe
    then
      set is_wsl = 1
      echo "Executing `dirname $0`/bootstrap-wsl"
      `dirname $0`/bootstrap-wsl
    fi
    ;;
  *)
    ;;
esac;

if [ $is_linux ]; then
  if test ! $(which az)
  then
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  fi
fi

if [ ! -d ~/.nvm ]
then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm install --lts
fi

# Node-based tools

if test ! $(which eslint)
then
  npm install -g eslint
fi

if test ! $(which func)
then
  npm install -g azure-functions-core-tools --unsafe-perm true
fi

if test ! $(which netlify)
then
  npm install -g netlify-cli
fi

if test ! -f ~/.netlify/helper/bin/git-credential-netlify
then
  netlify plugins:install netlify-lm-plugin
fi

if test ! $(which prettier)
then
  npm install -g prettier
fi

if test ! $(which tsc)
then
  npm install -g typescript
fi

# Rust

if [ ! -f ~/.cargo/bin/rustup ]
then
  curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path
fi


