#!/bin/bash

if test ! $(which eslint)
then
  npm install -g eslint
fi

if test ! $(which func)
then
  npm install -g azure-functions-core-tools --unsafe-perm true
fi

if test ! $(which netlify)
then
  npm install -g netlify-cli
fi

if test ! $(which prettier)
then
  npm install -g prettier
fi

if test ! $(which tsc)
then
  npm install -g typescript
fi