#!/bin/bash

brew upgrade
brew update

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi

# Source code folder index blocker
mkdir -p ~/Source
touch ~/Source/.metadata_never_index

# System Preferences should not be around when we do this
osascript -e 'tell application "System Preferences" to quit'

# Screen Saver Lock
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Turn on Firewall
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist 2>/dev/null

# FileVault
if [[ `fdesetup status` != "FileVault is On." ]]
then
  echo "⚠️ FileVault will be enabled."
  sudo fdesetup enable -user $USER 
fi

# Safari
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false


# Dock
defaults write com.apple.dock autohide -bool true


# Finder
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Time Machine
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Login text
LOGIN_TEXT="Found this computer? Please contact Duncan Davidson at duncandavidson@me.com"
sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "$LOGIN_TEXT"

# Coda
echo "You may need to log out/in for some MacOS settings to take effect"