#!/bin/bash

if [ ! -f /etc/apt/sources.list.d/git-core-ubuntu-ppa-bionic.list ]
then
  sudo add-apt-repository ppa:git-core/ppa
fi

if [ ! -f /etc/apt/sources.list.d/github_git-lfs.list ]
then
  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
fi

sudo apt-get update
sudo apt-get upgrade -y

sudo apt-get install -y \
  git \
  git-lfs \
  jq \
  direnv \
  htop